version: "3"

volumes:
  terminusdb_storage:

services:
  terminusdb-server:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb-server
    hostname: terminusdb-server
    tty: true
    ports:
      - 6363:6363
    environment:
      - TERMINUSDB_SERVER_PORT=6363

      # There are multiple ways to configure TerminusDB security through
      # environment variables. Several reasonable options are included below.
      # Uncomment the option you decide on and comment out others.
      # Don't forget to change the default password!

      # Security Option 1: TerminusDB is set up behind a TLS-terminating reverse
      # proxy with admin authentication provided by password.
      # - TERMINUSDB_PUBLIC_URL=https://example.com
      # - TERMINUSDB_ADMIN_PASS=root  #  Change before exposing to the internet.

    # Volumes mounted to the container.
    # Syntax is `[SOURCE:]TARGET[:MODE]` See: https://docs.docker.com/compose/compose-file/#volumes
    # SOURCE: host filesystem path or volume name. TARGET: container filesystem path
