.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "TERMINUSDB" "1" "November 2021" "" ""
.SH "NAME"
\fBterminusdb\fR \- command line interface to the terminusdb Graph DBMS
.SH "SYNOPSIS"
\fBterminusdb [command subcommand positional_arguments] flags\fR
.SH "DESCRIPTION"
The terminusdb(1) command line tool allows users to interact with a database, allowing common operations such as querying (and updating), database creation, data ingestion and maintainence\.
.SH "COMMANDS"
terminusdb accepts a command, sometimes followed by a subcommand\. The accepted commands are given here, along with their arguments\.
.SH "SYNTAX"
The designation of databases, repositories, the associated commit graph of a database, and various graphs as used in the above command requires the use of an appropriate descriptor path\.
.TP
\fB_system\fR
This is the system meta\-data, which contains the user information, organization information and database records\.
.TP
\fB<organization>/<database>\fR
This is the most basic descriptor path and actually refers to the more specific default path \fB<organization>/<database>/local/branch/main\fR\.
.TP
\fB<organization>/<database>/_meta\fR
This is the repository graph associated with \fBdatabase\fR\. It contains information about the local repository and all known remotes\.
.TP
\fB<organization>/<database>/<repository>\fR
This is a longer form database designator which specifies which respository we would like to address\. It refers implicitly to \fB<organization>/<database>/<repository>/branch/main\fR\.
.TP
\fB<organization>/<database>/<repository>/_commits\fR
The commit graph associated with a given database\. This graph contains metadata about branch histories with their commit objects including the authorship and time\.
.TP
\fB<organization>/<database>/<repository>/branch/<branch>\fR
The most specific branch descriptor, allows you to address a branch other than main\.
.TP
\fB<organization>/<database>/<repository>/commit/<commit>\fR
The descriptor which allows an individual commit to be addressed directly\.
.SH "ENVIRONMENT"
.TP
\fBTERMINUSDB_SERVER_NAME\fR
Set the servername to use for\fBterminusdb serve\fR\. Default is \fB127\.0\.0\.1\fR\.
.TP
\fBTERMINUSDB_SERVER_PORT\fR
Set the port to use for\fBterminusdb serve\fR\. Default is \fB6363\fR\.
.TP
\fBTERMINUSDB_SERVER_WORKERS\fR
Set the number of worker threads to use for \fBterminusdb serve\fR\. Default is \fB8\fR\.
.TP
\fBTERMINUSDB_SERVER_MAX_TRANSACTION_RETRIES\fR
Set the transaction retry count\. Default is \fB3\fR\.
.TP
\fBTERMINUSDB_SERVER_DB_PATH\fR
Set the location of the storage volume to be used by \fBterminusdb\fR operations\. Can be addressed relative to current path using \fB\./\fR\fIpath\fR\. Default is \fB\./storage/db\fR\.
.TP
\fBTERMINUSDB_SERVER_JWT_PUBLIC_KEY_PATH\fR
Set the public key path for JWT\. Default is \fB\'\'\fR\.
.TP
\fBTERMINUSDB_SERVER_JWT_PUBLIC_KEY_ID\fR
Set the public key identifier for JWT\. Default is \fB\'\'\fR\.
.TP
\fBTERMINUSDB_CONSOLE_BASE_URL\fR
Set the console javascript load URL\. Default is \fBhttps://cdn\.terminusdb\.com/js_libs/terminusdb_console/dev\fR\.
.TP
\fBTERMINUSDB_AUTOLOGIN_ENABLED\fR
If \fBtrue\fR then attempt to login automatically with default password\. Default is \fBtrue\fR\.
.TP
\fBTERMINUSDB_SERVER_PACK_DIR\fR
Location of the prolog pack directory if loading third party modules\.
.TP
\fBTERMINUSDB_SERVER_TMP_PATH\fR
Path to use for temporary files\.
.TP
\fBTERMINUSDB_IGNORE_REF_AND_REPO_SCHEMA\fR
Assume that ref and repo operations are inherently correct\.
.SH "EXIT STATUS"
.TP
0
Successfully program execution\. Associated with \fBapi:success\fR\.
.TP
1
A generic failure of the API to carry out the operation\. Associated with \fBapi:failure\fR\.
.TP
2
The resource which was being requested was not found\. Associated with \fBapi:not_found\fR\.
.TP
13
The user attempted to carry out an operation without appropriately authorizing or without permission\. Associated with \fBapi:unauthorized\fR or \fBapi:forbidden\fR\.
.TP
13
Unauthorized access attempted\. Associated with \fBapi:unauthorized\fR\.
.TP
126
An api command was attempted which is not possible\. Associated with \fBapi:method_not_allowed\fR\.
.TP
131
Internal server error\. Associated with \fBapi:server_error\fR\.
.SH "EXAMPLES"
.TP
\fBterminusdb db create admin/foo\fR
Create a database in the organization \fBadmin\fR with the identifier \fBfoo\fR\.
.TP
\fBterminusdb db create admin/foo \-\-label="Foo"\fR
Create a database in the organization \fBadmin\fR with the identifier \fBfoo\fR and name \fBFoo\fR\.
.SH "COPYRIGHT"
Copyright 2021 TerminusDB
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at
.P
http://www\.apache\.org/licenses/LICENSE\-2\.0
.P
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\. See the License for the specific language governing permissions and limitations under the License\.
.SH "AUTHORS"
Gavin Mendel\-Gleason \fI\%mailto:gavin@terminusdb\.com\fR
.P
Matthijs van Otterdijk \fI\%mailto:matthijs@terminusdb\.com\fR
.P
Robin de Rooij \fI\%mailto:robin@terminusdb\.com\fR
.P
Anne Ogborn \fI\%mailto:anne@swi\-prolog\.org\fR
.P
Dmytri Kleiner \fI\%mailto:dk@terminusdb\.com\fR
.P
Paulo Moura \fI\%https://github\.com/pmoura\fR
